### ISSUE TITLE
ToObject on non public classes failed

### ISSUE THREAD

**Issue by detlefm** [mgholam/fastJSON#82]
``` 
 class MyTest {
        public string StringOne { get; set; }
        public string StringTwo { get; set; }
        public int IntOne { get; set; }
        static public string JsonText() {
            return "{ \"StringOne\":\"Hello world\",\"StringTwo\":\"FastJson\",\"IntOne\":15}";
        }
    }
// this throws an exception
 MyTest t = fastJSON.JSON.ToObject<MyTest>(MyTest.JsonText());

with public class MyTest {} it works.

NewtonSoft has no problems with non-public classes.

Here is the Exception:
System.Exception
  HResult=0x80131500
  Message=Failed to fast create instance for type 'consoletest.MyTest' from assembly 'consoletest.MyTest, consoletest, Version=1.0.6751.22009, Culture=neutral, PublicKeyToken=null'
  Source=fastJSON
  StackTrace:
   at fastJSON.Reflection.FastCreateInstance(Type objtype)
   at fastJSON.deserializer.ParseDictionary(Dictionary`2 d, Dictionary`2 globaltypes, Type type, Object input)
   at fastJSON.deserializer.ToObject(String json, Type type)
   at fastJSON.deserializer.ToObject[T](String json)
   at consoletest.Program.Main(String[] args) in C:\Users\meyer\Documents\Projects\git\fastJSON\consoletest\Program.cs:line 38

Inner Exception 1:
TypeAccessException: Fehler beim Versuch der Methode "DynamicClass._()", auf Typ "consoletest.MyTest" zuzugreifen.

**Comment by mgholam** [comment]
Fixed in v2.1.34
